name: Python application

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  NUMBER_LOGIN: ${{ secrets.NUMBER_LOGIN }}
  PASSWORD_LOGIN: ${{ secrets.PASSWORD_LOGIN }}
  NUMBER_SEND: ${{ secrets.NUMBER_SEND }}
  PASSWORD_SEND: ${{ secrets.PASSWORD_SEND }}

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Set up ChromeDriver
      run: |
        sudo apt-get install -y unzip xvfb libxi6 libgconf-2-4
        wget -N https://chromedriver.storage.googleapis.com/2.41/chromedriver_linux64.zip
        unzip chromedriver_linux64.zip -d /usr/local/bin/
        sudo mv -f /usr/local/bin/chromedriver /usr/bin/chromedriver
        sudo chmod +x /usr/bin/chromedriver
    - name: Run tests
      run: |
        pytest -v -s --alluredir results